language: php

cache:
  directories:
    - $HOME/.composer/cache

php:
  - 5.5
  - 5.6
  - 7.1
  env: DEPENDENCIES=beta

before_script:
    - curl -s http://getcomposer.org/installer | php
    - php composer.phar install --dev
    - if [ "$DEPENDENCIES" = "beta" ]; then composer config minimum-stability beta; fi;

script: phpunit --coverage-clover clover

after_success:
    - curl -sL https://bit.ly/artifact-uploader | php
