language: php

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  fast_finish: true
  include:
    - php: 5.5
    - php: 5.6
    - php: 7.0
    - php: 7.1
      env: DEPENDENCIES=beta
    - php: hhvm
  allow_failures:
    - php: hhvm  

before_script:
  - if [ "$DEPENDENCIES" = "beta" ]; then composer config minimum-stability beta; fi;

install: composer update --prefer-dist --no-interaction --prefer-stable

script: phpunit --coverage-clover clover

after_success:
    - curl -sL https://bit.ly/artifact-uploader | php
